version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  mongodb-community-server:
    user: mongodb
    environment:
        - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - HOME=/data/db
    volumes:
        - /data/configdb
        - /data/db
    ports:
        - 27017:27017
    labels:
        - description=Container configured with a standalone instance of
          MongoDB
        - maintainer=support@mongodb.com
        - name=MongoDB Standalone
        - org.opencontainers.image.ref.name=ubuntu
        - org.opencontainers.image.version=22.04
        - summary=MongoDB Standalone Container
        - vendor=MongoDB
        - version=6.0.8
    runtime: runc
    image: mongodb/mongodb-community-server:6.0.8-ubuntu2204